-- MySQL Script generated by MySQL Workbench
-- Sat Nov  7 04:13:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prontaform
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prontaform` ;

-- -----------------------------------------------------
-- Schema prontaform
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prontaform` DEFAULT CHARACTER SET utf8 ;
USE `prontaform` ;

-- -----------------------------------------------------
-- Table `prontaform`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`area` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(90) NOT NULL,
  `state` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`catalogStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`catalogStatus` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`catalogStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`client` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `agent` VARCHAR(80) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zipcode` INT NOT NULL,
  `city` VARCHAR(90) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`delivery` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`delivery` (
  `id` INT NOT NULL,
  `user` INT NOT NULL,
  `deliveryDate` DATETIME NOT NULL,
  `area` INT NOT NULL,
  INDEX `uduser_idx` (`user` ASC) VISIBLE,
  INDEX `udarea_idx` (`area` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `uduser`
    FOREIGN KEY (`user`)
    REFERENCES `prontaform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `udarea`
    FOREIGN KEY (`area`)
    REFERENCES `prontaform`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`level` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`level` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`locate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`locate` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`locate` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`product` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `costoEntrega` DECIMAL(10,2) NOT NULL,
  `costoDevolucion` DECIMAL(10,2) NOT NULL,
  `Peso` DECIMAL(7,4) NOT NULL,
  `comisionEntrega` DECIMAL(10,2) NOT NULL,
  `comisionDevolucion` DECIMAL(10,2) NOT NULL,
  `tiempoCierre` INT NOT NULL,
  `nivelServicio` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idClient` ASC) VISIBLE,
  CONSTRAINT `clienteProducto`
    FOREIGN KEY (`idClient`)
    REFERENCES `prontaform`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`relPlace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`relPlace` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`relPlace` (
  `id` INT NOT NULL,
  `locate` INT NULL,
  `warehouse` INT NULL,
  `level` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `bodega_idx` (`warehouse` ASC) VISIBLE,
  INDEX `ubicacion_idx` (`locate` ASC) VISIBLE,
  INDEX `nivel_idx` (`level` ASC) VISIBLE,
  CONSTRAINT `bodega`
    FOREIGN KEY (`warehouse`)
    REFERENCES `prontaform`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ubicacion`
    FOREIGN KEY (`locate`)
    REFERENCES `prontaform`.`locate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nivel`
    FOREIGN KEY (`level`)
    REFERENCES `prontaform`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`remesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`remesa` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`remesa` (
  `remesa` INT NOT NULL,
  `dateArrive` DATETIME NOT NULL,
  `dateClose` DATETIME NOT NULL,
  `idclient` INT NOT NULL,
  `unitCount` INT NOT NULL,
  `mountTot` DECIMAL(7,2) NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`remesa`),
  INDEX `rClient_idx` (`idclient` ASC) VISIBLE,
  INDEX `rStatus_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `rClient`
    FOREIGN KEY (`idclient`)
    REFERENCES `prontaform`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rStatus`
    FOREIGN KEY (`status`)
    REFERENCES `prontaform`.`catalogStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`storage` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`storage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `place` INT NOT NULL,
  `unit` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wUnit_idx` (`unit` ASC) VISIBLE,
  INDEX `wPlace_idx` (`place` ASC) VISIBLE,
  CONSTRAINT `wUnit`
    FOREIGN KEY (`unit`)
    REFERENCES `prontaform`.`unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wPlace`
    FOREIGN KEY (`place`)
    REFERENCES `prontaform`.`relPlace` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`unit` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idstatus` INT NOT NULL,
  `remesa` INT NOT NULL,
  `barcode` VARCHAR(20) NOT NULL,
  `idProduct` INT NOT NULL,
  `mount` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `uProduct_idx` (`idProduct` ASC) VISIBLE,
  INDEX `uStatus_idx` (`idstatus` ASC) VISIBLE,
  INDEX `uRemesa_idx` (`remesa` ASC) VISIBLE,
  CONSTRAINT `uProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `prontaform`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uStatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `prontaform`.`catalogStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uRemesa`
    FOREIGN KEY (`remesa`)
    REFERENCES `prontaform`.`remesa` (`remesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`unitDelivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`unitDelivery` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`unitDelivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unit` INT NOT NULL,
  `delivery` INT NOT NULL,
  `visitStatus` INT NOT NULL,
  `reason` INT NULL,
  `visitDate` DATETIME NULL,
  `comment` VARCHAR(255) NULL,
  `isMount` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `udDelivery_idx` (`delivery` ASC) VISIBLE,
  INDEX `udUnit_idx` (`unit` ASC) VISIBLE,
  INDEX `udStatus_idx` (`visitStatus` ASC) VISIBLE,
  INDEX `udReason_idx` (`reason` ASC) VISIBLE,
  CONSTRAINT `udStatus`
    FOREIGN KEY (`visitStatus`)
    REFERENCES `prontaform`.`catalogStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `udDelivery`
    FOREIGN KEY (`delivery`)
    REFERENCES `prontaform`.`delivery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `udUnit`
    FOREIGN KEY (`unit`)
    REFERENCES `prontaform`.`unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `udReason`
    FOREIGN KEY (`reason`)
    REFERENCES `prontaform`.`catalogStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`user` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idType` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `utype_idx` (`idType` ASC) VISIBLE,
  CONSTRAINT `utype`
    FOREIGN KEY (`idType`)
    REFERENCES `prontaform`.`userType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prontaform`.`userDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`userDetail` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`userDetail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idProntaform` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`iduser`)
    REFERENCES `prontaform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`userPermissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`userPermissions` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`userPermissions` (
  `iduser` INT NOT NULL,
  `recoleccion` VARCHAR(45) NULL,
  `recibo` VARCHAR(45) NULL,
  `inventario` VARCHAR(45) NULL,
  `despacho` VARCHAR(45) NULL,
  `catalogos` VARCHAR(45) NULL,
  `usuarios` VARCHAR(45) NULL,
  `manifiestos` VARCHAR(45) NULL,
  `reportes` VARCHAR(45) NULL,
  INDEX `pUser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `pUser`
    FOREIGN KEY (`iduser`)
    REFERENCES `prontaform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`userType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`userType` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`userType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontaform`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prontaform`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `prontaform`.`warehouse` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
